-- Fábrica editorial RH Cursos: pauta inicial de eSocial, folha e DP público.
-- Todos os itens são rascunhos e não são expostos pela policy pública de post_blog.
-- A migration não altera rascunhos que já tenham sido editados no administrativo.
-- O vínculo ao curso é aplicado quando o curso prioritário já existe no catálogo;
-- caso contrário, o rascunho continua válido e pode ser vinculado no administrativo.

with drafts (
  id, titulo, slug, resumo, conteudo, categoria, tags, autor, tempo_leitura, status, imagem_url, target_curso_id
) as (
values
  ('post-fabrica-esocial-01', 'O que muda na rotina dos órgãos públicos com o eSocial S-1.3', 'o-que-muda-na-rotina-dos-orgaos-publicos-com-o-esocial-s-1-3', 'Quatro perguntas que a equipe deve responder antes de ajustar sistemas, cadastros e conferências do eSocial.', 'Antes de atualizar o eSocial, o órgão precisa responder a quatro perguntas: quais dados mudam, quem responde por cada dado, em qual sistema a informação nasce e quem confere o resultado antes do envio. Sem esse mapa, a correção fica presa a quem percebeu o erro por último.\n\nRH, Departamento Pessoal, folha, contabilidade, tecnologia e controle interno não precisam executar a mesma tarefa. Precisam saber quando recebem a informação, qual validação fazem e para quem devolvem uma pendência. Registre essas passagens em um fluxo simples, com responsável e prazo.\n\nDepois confira os cadastros, as tabelas usadas pela folha e os eventos com maior volume. Dados incompletos costumam aparecer no fechamento como rejeição ou diferença de conferência, quando o tempo para corrigir já é menor.\n\nO Curso Prático de Atualização do eSocial aprofunda a parametrização, os eventos e a conferência aplicada à realidade dos órgãos públicos.', 'eSocial', '["esocial","setor público","leiaute s-1.3"]'::jsonb, 'Equipe RH Cursos', '6 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-esocial-s13-publico'),
  ('post-fabrica-esocial-02', 'Checklist para preparar a equipe antes da atualização do eSocial', 'checklist-para-preparar-a-equipe-antes-da-atualizacao-do-esocial', 'Seis frentes para preparar pessoas, dados e processo antes de uma mudança operacional no eSocial.', 'Nomeie uma pessoa responsável pelo plano e publique um calendário de revisão. Cada item precisa ter dono, prazo e evidência de conclusão; isso evita que RH, folha e tecnologia trabalhem sobre versões diferentes do mesmo cadastro.\n\nA revisão deve cobrir acessos ao ambiente, dados de trabalhadores e lotações, tabelas de rubricas, integração com a folha, eventos que exigem conferência e o tratamento das rejeições. Não é uma lista para marcar em uma tarde: é uma sequência de checagens que acompanha a preparação da competência.\n\nRegistre separadamente as dúvidas que dependem de análise jurídica, contábil ou do fornecedor do sistema. Assim, a equipe não tenta resolver por conta própria uma decisão que exige validação formal.\n\nNo curso de eSocial da RH Cursos, esse checklist é levado para a leitura do leiaute, a conferência de eventos e os casos de órgãos públicos.', 'eSocial', '["esocial","checklist","conformidade"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-esocial-s13-publico'),
  ('post-fabrica-esocial-03', 'Os erros de cadastro que geram retrabalho no eSocial', 'os-erros-de-cadastro-que-geram-retrabalho-no-esocial', 'Quais dados revisar antes que uma inconsistência alcance a folha e os eventos enviados.', 'Vínculo, matrícula, lotação, jornada e rubricas são exemplos de dados que acompanham o trabalhador por toda a rotina. Se um deles entra errado, a diferença pode aparecer na folha, na conferência ou no envio de eventos.\n\nEm vez de tentar revisar todos os campos com a mesma intensidade, escolha os campos críticos para cada grupo de trabalhador e defina uma conferência por exceção. Procure campos vazios, nomes diferentes para a mesma situação e alterações funcionais que ainda não chegaram ao sistema.\n\nQuando corrigir uma ocorrência, anote de onde ela veio e o que impediu a detecção anterior. Esse registro mostra se o problema foi pontual ou se o processo precisa de uma regra nova.\n\nO Curso Prático de Atualização do eSocial trabalha qualificação, eventos e saneamento de inconsistências em cenários de órgãos públicos.', 'eSocial', '["esocial","cadastro","saneamento de dados"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-esocial-s13-publico'),
  ('post-fabrica-esocial-04', 'Como organizar a conferência de eventos antes do envio ao eSocial', 'como-organizar-a-conferencia-de-eventos-antes-do-envio-ao-esocial', 'Uma sequência de fechamento para validar dados, corrigir exceções e registrar evidências antes da transmissão.', 'Separe o fechamento em três momentos: validar os dados de origem, corrigir as exceções encontradas e confirmar o que será transmitido. Quando essas atividades acontecem ao mesmo tempo, a equipe perde a trilha do que foi revisado e do que ainda depende de correção.\n\nDefina os eventos e totalizadores que exigem atenção em cada competência. Para cada um, indique quem compara o dado de origem com o sistema e qual comprovante ficará guardado após a conferência.\n\nSe houver diferença, volte à origem antes de alterar o resultado. Cadastro, regra de folha, integração e evento anterior podem produzir o mesmo sintoma, mas pedem correções diferentes.\n\nA oficina prática do curso de eSocial ajuda a montar esse fluxo e a trabalhar ocorrências reais de conferência.', 'eSocial', '["esocial","eventos","conferência mensal"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-esocial-s13-publico'),
  ('post-fabrica-folha-01', 'Auditoria da folha de pagamento: por onde começar', 'auditoria-da-folha-de-pagamento-por-onde-comecar', 'Como definir escopo, selecionar evidências e transformar achados em um plano de correção.', 'Uma auditoria começa pela pergunta que a equipe precisa responder. Pode ser conferir uma mudança de processo, investigar uma diferença recorrente, revisar uma rubrica ou atender a uma demanda de controle interno. Essa pergunta define o recorte do trabalho.\n\nEscolha o período, os grupos de trabalhadores, as rubricas e os documentos que entrarão na revisão. Jornada, férias, adicionais, descontos, encargos e rescisões exigem evidências diferentes; juntar tudo em uma única checagem costuma esconder o que importa.\n\nPara cada achado, registre a evidência, o impacto, quem fará a análise e qual correção foi combinada. Com isso, a equipe distingue uma ocorrência isolada de uma falha de parametrização ou de processo.\n\nO Curso de Auditoria da Folha de Pagamento apresenta essa metodologia aplicada a rubricas, bases de cálculo, jornada e riscos.', 'Folha de Pagamento', '["auditoria da folha","riscos trabalhistas","controles"]'::jsonb, 'Equipe RH Cursos', '6 min', 'Rascunho', '/images/courses/auditoria-tributaria.jpg', 'course-2026-auditoria-folha'),
  ('post-fabrica-folha-02', 'Checklist de auditoria de rubricas e encargos da folha', 'checklist-de-auditoria-de-rubricas-e-encargos-da-folha', 'O que verificar para entender a regra de uma rubrica antes de comparar valores e incidências.', 'Comece pela ficha da rubrica: finalidade, trabalhadores alcançados, regra de cálculo e documentos que sustentam o lançamento. Sem essa referência, comparar números não revela se a diferença veio da regra, do dado de origem ou da parametrização.\n\nEm seguida, confira base de cálculo, incidências, descontos e reflexos. Itens extraordinários merecem uma trilha própria de análise porque podem não seguir a recorrência da folha mensal.\n\nClassifique cada diferença por impacto, urgência, recorrência e necessidade de consulta especializada. A classificação ajuda a equipe a priorizar correções e a documentar o que ainda depende de decisão técnica.\n\nO Curso de Auditoria da Folha de Pagamento usa casos e simulações para exercitar esses controles na rotina profissional.', 'Folha de Pagamento', '["rubricas","encargos","checklist de auditoria"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/auditoria-tributaria.jpg', 'course-2026-auditoria-folha'),
  ('post-fabrica-folha-03', 'Como identificar inconsistências na jornada antes que virem passivo', 'como-identificar-inconsistencias-na-jornada-antes-que-virem-passivo', 'Sinais que justificam conferir jornada, ponto, intervalos e exceções antes do fechamento da folha.', 'Para conferir jornada, coloque lado a lado a regra aplicável, os registros disponíveis e os lançamentos que chegaram à folha. Se as três fontes contam histórias diferentes, a equipe precisa descobrir a razão antes de fechar a competência.\n\nObserve exceções repetidas, marcações incompletas, mudanças de escala, horas extras frequentes e aprovações fora do fluxo. Esses sinais não provam uma irregularidade; indicam onde a revisão deve começar.\n\nRegistre a evidência e discuta o contexto com as áreas responsáveis. Algumas correções dependem de decisão administrativa ou de análise técnica, e não devem ser tratadas como simples ajuste automático.\n\nO Curso de Auditoria da Folha de Pagamento aborda jornada, ponto, intervalos e os reflexos dessas informações na folha.', 'Folha de Pagamento', '["jornada","ponto","auditoria preventiva"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/auditoria-tributaria.jpg', 'course-2026-auditoria-folha'),
  ('post-fabrica-folha-04', 'O papel do controle interno na revisão da folha de pagamento', 'o-papel-do-controle-interno-na-revisao-da-folha-de-pagamento', 'Como organizar critérios, evidências e acompanhamento para que a revisão da folha resulte em correção.', 'O controle interno agrega valor quando define como a folha será revisada e acompanha o que aconteceu depois do achado. RH, DP, contabilidade e jurídico continuam responsáveis pelas decisões de suas áreas; o controle organiza a visão de risco e evidência.\n\nA rotina pode usar amostras, indicadores de exceção, documentos de suporte e uma periodicidade acordada. Para cada ponto revisado, deixe explícito quem analisa, quem aprova a medida e quando o resultado será conferido novamente.\n\nUm relatório útil informa o que foi verificado, o que foi encontrado, o impacto possível e a providência prevista. Assim, a auditoria não termina em uma lista de observações sem responsável.\n\nA formação em Auditoria da Folha de Pagamento prepara profissionais para mapear riscos e acompanhar planos de correção.', 'Gestão Pública', '["controle interno","folha de pagamento","gestão de riscos"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/auditoria-tributaria.jpg', 'course-2026-auditoria-folha'),
  ('post-fabrica-dp-01', 'Departamento Pessoal na Administração Pública: quais rotinas exigem maior controle', 'departamento-pessoal-na-administracao-publica-quais-rotinas-exigem-maior-controle', 'Onde concentrar controles no ciclo de admissão, movimentações, folha, obrigações e encerramentos.', 'O Departamento Pessoal alimenta a vida funcional, a folha e as obrigações do órgão. Por isso, vale enxergar o trabalho como um ciclo: a informação entra na admissão, sofre alterações ao longo do vínculo e reaparece no fechamento e nas entregas mensais.\n\nAdmissão, alteração funcional, jornada, afastamento, remuneração, férias e rescisão precisam de dados consistentes e de uma pessoa responsável por cada passagem. Uma mudança não registrada na origem pode reaparecer semanas depois como diferença de folha ou pendência de obrigação.\n\nPara definir prioridades, observe onde há mais exceções, retrabalho ou dependência de uma única pessoa. Esses são os pontos que pedem procedimento, checklist e treinamento antes de ganhar uma solução complexa.\n\nO Curso de Departamento Pessoal Completo para Administração Pública percorre esse ciclo com casos práticos e foco em controle.', 'Departamento Pessoal', '["departamento pessoal","administração pública","rotinas"]'::jsonb, 'Equipe RH Cursos', '6 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-dp-completo-publica'),
  ('post-fabrica-dp-02', 'Admissão, jornada e licenças: como organizar processos de DP no setor público', 'admissao-jornada-e-licencas-como-organizar-processos-de-dp-no-setor-publico', 'Como definir dados, responsáveis e evidências antes de cada movimentação de pessoal.', 'Para cada admissão, alteração de jornada ou licença, a equipe precisa saber quais documentos recebe, quem valida, quem aprova, onde registra e quais áreas devem ser avisadas. Esse roteiro reduz a dependência de orientações verbais e de memória individual.\n\nA informação deve chegar à folha e aos sistemas envolvidos pelo mesmo caminho em todos os casos equivalentes. Formulário incompleto, aprovação sem registro e lançamento fora do prazo são sinais de que o fluxo precisa ser revisto.\n\nSituações especiais não devem desaparecer dentro do processo padrão. Registre a exceção, a decisão tomada e os sistemas que precisam refletir essa decisão.\n\nA formação de Departamento Pessoal da RH Cursos conecta admissão, jornada, folha, licenças e controles para a rotina do setor público.', 'Departamento Pessoal', '["admissão","jornada","licenças"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-dp-completo-publica'),
  ('post-fabrica-dp-03', 'FGTS Digital, DCTFWeb/MIT e EFD-Reinf: como coordenar as obrigações sem retrabalho', 'fgts-digital-dctfweb-mit-e-efd-reinf-como-coordenar-as-obrigacoes-sem-retrabalho', 'Como alinhar dados, conferências e evidências das obrigações que dependem da folha.', 'A mesma informação da folha pode alimentar mais de uma obrigação. Se cada entrega for conferida isoladamente, a equipe tende a descobrir uma divergência tarde e a corrigir apenas o resultado que apareceu primeiro.\n\nMonte um mapa com três colunas: dado de origem, sistema ou evento que o utiliza e comprovante que deve ser arquivado. Depois distribua o calendário mensal entre preparação de dados, conferência, tratamento de exceções e confirmação de entrega.\n\nQuando dois sistemas apresentarem números diferentes, procure a origem em cadastros, rubricas, eventos e parametrizações antes de ajustar o valor final. O tratamento depende do contexto de cada órgão e pode exigir validação técnica.\n\nO Curso de Departamento Pessoal Completo trabalha a integração entre folha, eSocial, DCTFWeb/MIT, FGTS Digital, EFD-Reinf e controle interno.', 'Departamento Pessoal', '["FGTS Digital","DCTFWeb","EFD-Reinf"]'::jsonb, 'Equipe RH Cursos', '6 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-dp-completo-publica'),
  ('post-fabrica-dp-04', 'Como estruturar uma rotina de conferência mensal da folha pública', 'como-estruturar-uma-rotina-de-conferencia-mensal-da-folha-publica', 'Um roteiro de fechamento que distribui preparação, validação, correção e evidências ao longo da competência.', 'A conferência mensal começa antes do processamento da folha. Reserve datas para receber movimentações, validar dados de origem, processar, analisar exceções e documentar o fechamento. A agenda torna visível o que ainda depende de outra área.\n\nUse poucos controles, mas mantenha-os estáveis: comparação de variações relevantes, revisão de rubricas críticas, verificação de afastamentos e admissões, conciliação das informações que seguem para obrigações e registro de pendências.\n\nNo fim do ciclo, anote o que foi conferido, quais exceções surgiram, qual decisão foi tomada e quem permanece responsável por cada ação aberta. Esse histórico reduz a repetição de correções informais.\n\nNo Curso de Departamento Pessoal Completo, os participantes conectam esse roteiro à rotina de folha, aos sistemas oficiais e ao controle interno.', 'Departamento Pessoal', '["folha pública","fechamento mensal","controle interno"]'::jsonb, 'Equipe RH Cursos', '5 min', 'Rascunho', '/images/courses/departamento-pessoal-esocial.jpg', 'course-2026-dp-completo-publica')
)
insert into public.post_blog (
  id, titulo, slug, resumo, conteudo, categoria, tags, autor, tempo_leitura, status, imagem_url, curso_id
)
select
  d.id,
  d.titulo,
  d.slug,
  d.resumo,
  d.conteudo,
  d.categoria,
  d.tags,
  d.autor,
  d.tempo_leitura,
  d.status::public.status_post_blog,
  d.imagem_url,
  c.id
from drafts d
left join public.curso c
  on c.id = d.target_curso_id
 and c.deleted_at is null
on conflict (slug) do nothing;
